### ISSUE TITLE
zen quote api

### ISSUE THREAD

**Issue by MaxAFath** [rpodols/the-zen-project#1]
api call for zen

**Comment by rpodols** [comment]
added the quote page

this page also calls luxon api, which pulls the month and date in

i have a variable created that combines the month and date into 1 value, and that value is then indexed into the quote array so each day it pulls a different quote

i also added a user submitted quote area, where it has 1 preloaded quote if there hasn't been any submitted, otherwise has validation to make sure quote/author is entered, saved, and will then display at random
